import{a as P,S as v,i as E}from"./assets/vendor-DU3R_DxZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const $="42598065-1779ad5a953180c3fe77c2809",q="https://pixabay.com/api/";async function p(t,o=1,i=15){const n={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:i};return(await P.get(q,{params:n})).data}let L;function S(t){return t.map(({webformatURL:o,largeImageURL:i,tags:n,likes:e,views:r,comments:s,downloads:M})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img src="${o}" alt="${n}" loading="lazy" />
        </a>
        <ul>
          <li>Likes: ${e}</li>
          <li>Views: ${r}</li>
          <li>Comments: ${s}</li>
          <li>Downloads: ${M}</li>
        </ul>
      </li>`).join("")}function x(t){t.innerHTML=""}function w(){document.querySelector(".loader").classList.remove("hidden")}function u(){document.querySelector(".loader").classList.add("hidden")}function O(){document.querySelector(".load-more").classList.remove("hidden")}function b(){document.querySelector(".load-more").classList.add("hidden")}function A(){L=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){L.refresh()}const c={info:"Please enter a value in the search field!",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there is no connection to the server. Try again later!",exception:"Something went wrong. Please try again later!",end:"We're sorry, but you've reached the end of search results."},l={blue:"#abd4f8",orange:"#f28111",red:"#e97782"};function d(t,o){E.info({position:"topRight",backgroundColor:o,message:t})}const g=document.querySelector(".search-form"),f=document.querySelector(".gallery"),D=document.querySelector(".load-more");let a=1,y="",m=0;const h=15;g.addEventListener("submit",async t=>{t.preventDefault(),b(),x(f),w();const i=new FormData(g).get("search").trim();if(!i){u(),d(c.info,l.blue);return}y=i,a=1;try{const n=await p(y,a,h);if(m=n.totalHits,n.hits.length===0){u(),d(c.warning,l.red);return}f.innerHTML=S(n.hits),A(),a<Math.ceil(m/h)&&O()}catch(n){d(`${c.exception} ${n}`,l.orange)}finally{u()}});D.addEventListener("click",async()=>{a+=1,w();try{const t=await p(y,a,h);f.insertAdjacentHTML("beforeend",S(t.hits)),B();const{height:o}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),a>=Math.ceil(m/h)&&(b(),d(c.end,l.red))}catch(t){d(`${c.exception} ${t}`,l.orange)}finally{u()}});
//# sourceMappingURL=index.js.map
