import{a as M,S as v,i as E}from"./assets/vendor-DU3R_DxZ.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const $="42598065-1779ad5a953180c3fe77c2809",q="https://pixabay.com/api/";async function p(t,n=1,i=15){const r={key:$,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:i};return(await M.get(q,{params:r})).data}let L;function S(t){return t.map(({webformatURL:n,largeImageURL:i,tags:r,likes:e,views:o,comments:s,downloads:P})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img src="${n}" alt="${r}" loading="lazy" />
        </a>
        <ul>
          <li>Likes: ${e}</li>
          <li>Views: ${o}</li>
          <li>Comments: ${s}</li>
          <li>Downloads: ${P}</li>
        </ul>
      </li>`).join("")}function x(t){t.innerHTML=""}function w(){document.querySelector(".loader").classList.remove("hidden")}function u(){document.querySelector(".loader").classList.add("hidden")}function O(){document.querySelector(".load-more").classList.remove("hidden")}function b(){document.querySelector(".load-more").classList.add("hidden")}function A(){L=new v(".gallery a",{captionsData:"alt",captionDelay:250})}function B(){L.refresh()}const c={info:"Please enter a value in the search field!",warning:"Sorry, there are no images matching your search query. Please try again!",error:"Sorry, there is no connection to the server. Try again later!",exception:"Something went wrong. Please try again later!",end:"We're sorry, but you've reached the end of search results."},l={blue:"#abd4f8",orange:"#f28111",red:"#e97782"};function d(t,n){E.info({position:"topRight",backgroundColor:n,message:t})}const g=document.querySelector(".search-form"),f=document.querySelector(".gallery"),D=document.querySelector(".load-more");let a=1,m="",y=0;const h=15;g.addEventListener("submit",async t=>{t.preventDefault(),b(),x(f),w(),await new Promise(r=>setTimeout(r,50));const i=new FormData(g).get("search").trim();if(!i){u(),d(c.info,l.blue);return}m=i,a=1;try{const r=await p(m,a,h);if(y=r.totalHits,r.hits.length===0){u(),d(c.warning,l.red);return}f.innerHTML=S(r.hits),A(),a<Math.ceil(y/h)&&O()}catch(r){d(`${c.exception} ${r}`,l.orange)}finally{u()}});D.addEventListener("click",async()=>{a+=1,w();try{const t=await p(m,a,h);f.insertAdjacentHTML("beforeend",S(t.hits)),B();const{height:n}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:n*2,behavior:"smooth"}),a>=Math.ceil(y/h)&&(b(),d(c.end,l.red))}catch(t){d(`${c.exception} ${t}`,l.orange)}finally{u()}});
//# sourceMappingURL=index.js.map
